# Generated by Django 5.0.6 on 2024-06-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethereum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereumaddress',
            name='is_contract',
            field=models.BooleanField(default=False),
        ),
    ]
